### ISSUE TITLE
Error while using client.logout()

### ISSUE THREAD

**Issue by d0geda** [ValvePython/steam#108]
Hello, I've got this error for this piece of code:

Error:
```
Unhandled exception in thread started by <function processingOrder at 0x7f77467b8c80>
Traceback (most recent call last):
  File "SteamBot.py", line 272, in processingOrder
    client.logout()
  File "/usr/local/lib/python2.7/dist-packages/steam/client/__init__.py", line 557, in logout
    self.wait_event('disconnected')
  File "/usr/local/lib/python2.7/dist-packages/eventemitter/__init__.py", line 119, in wait_event
    return result.get(True, timeout)
  File "/usr/local/lib/python2.7/dist-packages/gevent/event.py", line 382, in get
    self._wait_core(timeout, ())
  File "/usr/local/lib/python2.7/dist-packages/gevent/event.py", line 106, in _wait_core
    result = self.hub.switch()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x7f77444ad9b0 epoll pending=0 ref=0 fileno=18 resolver=<gevent.resolver_thread.Resolver at 0x7f7745d3cdd0 pool=<ThreadPool at 0x7f7745d3ce50 0/2/10>> threadpool=<ThreadPool at 0x7f7745d3ce50 0/2/10>>)
```

Code:
```
if client.relogin_available:
    client.logout() 
    client.relogin()
```

**Comment by Zwork101** [comment]
Well, it would appear the lock was acquired twice. Does the same happen when you don't relogin?

**Comment by d0geda** [comment]
It appers just when I use `client.logout()`. And it has to be in the code. The bot works, it just prints out this message and I was wondering why.

**Comment by rossengeorgiev** [comment]
There isn't enough context to determine the issue. Looks like your instance is `logged_on = True`, but also `connected = False`. That shouldn't happen unless something is messed up. Do you have debug log ouput?

**Comment by d0geda** [comment]
The code works perfectly, I will probably leave it as it is.
