### ISSUE TITLE
CLI Example return gevent.hub.LoopExit error

### ISSUE THREAD

**Issue by kutu** [ValvePython/steam#127]
http://steam.readthedocs.io/en/latest/user_guide.html#cli-example

I've entered correct username, password, and code from email

```
Username: blabla
Password:
Enter email code: blabla
Traceback (most recent call last):
  File "steam_test.py", line 20, in <module>
    client.cli_login()
  File "D:\Python34\lib\site-packages\steam\client\__init__.py", line 633, in cli_login
    result = self.login(username, password, None, auth_code, two_factor_code)
  File "D:\Python34\lib\site-packages\steam\client\__init__.py", line 480, in login
    self._pre_login()
  File "D:\Python34\lib\site-packages\steam\client\__init__.py", line 415, in _pre_login
    self.wait_event("channel_secured")
  File "D:\Python34\lib\site-packages\eventemitter\__init__.py", line 119, in wait_event
    return result.get(True, timeout)
  File "D:\Python34\lib\site-packages\gevent\event.py", line 382, in get
    self._wait_core(timeout, ())
  File "D:\Python34\lib\site-packages\gevent\event.py", line 106, in _wait_core
    result = self.hub.switch()
  File "D:\Python34\lib\site-packages\gevent\hub.py", line 630, in switch
    return RawGreenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x4e58048 select default pending=0 ref=0 resolver=<gevent.resolver_thread.Resolver at 0x4e54f60 pool=<ThreadPool at 0x4e54f98 0/1/10>> threadpool=<ThreadPool at 0x4e54f98 0/1/10>>)
```

**Comment by rossengeorgiev** [comment]
Looks like some CMs servers are not responding properly.

Will need to handle that situation, and probably update the builtin bootstrap list.

**Comment by rossengeorgiev** [comment]
I've pushed a new release out with the fixes. Just update your package.

**Comment by kutu** [comment]
Thanks, it's working now.
