### ISSUE TITLE
Exceptions caused by (maybe) streaming

### ISSUE THREAD

**Issue by xire-** [ValvePython/steam#132]
Very rarely i get the following exception:
```
Traceback (most recent call last):
  File "/home/xire/project/venv/lib/python3.5/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/xire/project/venv/lib/python3.5/site-packages/steam/core/cm.py", line 330, in __handle_multi
    self._parse_message(data[4:4+size])
  File "/home/xire/project/venv/lib/python3.5/site-packages/steam/core/cm.py", line 259, in _parse_message
    self._LOG.debug("Incoming: %s", repr(msg))
UnboundLocalError: local variable 'msg' referenced before assignment
```

Logs contains:
```
SteamClient CRITICAL: Failed to deserialize message: EMsg.ServiceMethod (is_proto: True)
```

It seems the cause is an exception that is caught before `msg` is assigned.

https://github.com/ValvePython/steam/blob/80639f70cfdc72a03b145aba5247b2612a21f055/steam/core/cm.py#L244-L259

I think the messages that caused this were received when i tried to watch a stream with the real steam client on a different computer, but i didn't try to replicate it so i'm not sure.

---

At the same time i also get:
```
Traceback (most recent call last):
  File "/home/xire/project/venv/lib/python3.5/site-packages/steam/core/cm.py", line 246, in _parse_message
    msg = MsgProto(emsg, message)
  File "/home/xire/project/venv/lib/python3.5/site-packages/steam/core/msg/__init__.py", line 139, in __init__
    proto = get_um(self.header.target_job_name)
  File "/home/xire/project/venv/lib/python3.5/site-packages/steam/core/msg/unified.py", line 53, in get_um
    raise None
TypeError: exceptions must derive from BaseException
```
It seems this should be `return None`

**Comment by rossengeorgiev** [comment]
Thanks for the report @xire-
