### ISSUE TITLE
Logging issues with PM2 

### ISSUE THREAD

**Issue by Gobot1234** [ValvePython/steam#228]
I'm not really sure why this occurs but when using any form of logging with PM2 you get tonnes of errors from steam like:
```py
2|autocord   | --- Logging error ---
2|autocord   | Traceback (most recent call last):
2|autocord   |   File "C:\Users\James\Anaconda3\envs\tfbot\lib\logging\__init__.py", line 1025, in emit
2|autocord   |     msg = self.format(record)
2|autocord   |   File "C:\Users\James\Anaconda3\envs\tfbot\lib\logging\__init__.py", line 869, in format
2|autocord   |     return fmt.format(record)
2|autocord   |   File "C:\Users\James\Anaconda3\envs\tfbot\lib\logging\__init__.py", line 611, in format
2|autocord   |     s = self.formatMessage(record)
2|autocord   |   File "C:\Users\James\Anaconda3\envs\tfbot\lib\logging\__init__.py", line 580, in formatMessage
2|autocord   |     return self._style.format(record)
2|autocord   |   File "C:\Users\James\Anaconda3\envs\tfbot\lib\logging\__init__.py", line 422, in format
2|autocord   |     return self._fmt % record.__dict__
2|autocord   | ValueError: unsupported format character '{' (0x7b) at index 1
2|autocord   | Call stack:
2|autocord   |   File "C:\Users\James\PycharmProjects\tfdiscordbot\GoBOT1234\main.py", line 72, in handle_disconnect
2|autocord   |   File "C:\Users\James\Anaconda3\envs\tfbot\lib\site-packages\steam\client\__init__.py", line 234, in reconnect
2|autocord   |     return self.connect(delay=delay_seconds, retry=retry)
2|autocord   |   File "C:\Users\James\Anaconda3\envs\tfbot\lib\site-packages\steam\client\__init__.py", line 91, in connect
2|autocord   |     CMClient.connect(self, *args, **kwargs)
2|autocord   |   File "C:\Users\James\Anaconda3\envs\tfbot\lib\site-packages\steam\core\cm.py", line 117, in connect
2|autocord   |     self.emit(self.EVENT_RECONNECT, delay)
2|autocord   |   File "C:\Users\James\Anaconda3\envs\tfbot\lib\site-packages\steam\core\cm.py", line 94, in emit
2|autocord   |     self._LOG.debug("Emit event: %s" % repr(event))
2|autocord   | Message: "Emit event: 'reconnect'"
2|autocord   | Arguments: ()
2|autocord   | --- Logging error ---
2|autocord   | Traceback (most recent call last):
2|autocord   |   File "C:\Users\James\Anaconda3\envs\tfbot\lib\logging\__init__.py", line 1025, in emit
2|autocord   |     msg = self.format(record)
2|autocord   |   File "C:\Users\James\Anaconda3\envs\tfbot\lib\logging\__init__.py", line 869, in format
2|autocord   |     return fmt.format(record)
2|autocord   |   File "C:\Users\James\Anaconda3\envs\tfbot\lib\logging\__init__.py", line 611, in format
2|autocord   |     s = self.formatMessage(record)
2|autocord   |   File "C:\Users\James\Anaconda3\envs\tfbot\lib\logging\__init__.py", line 580, in formatMessage
2|autocord   |     return self._style.format(record)
2|autocord   |   File "C:\Users\James\Anaconda3\envs\tfbot\lib\logging\__init__.py", line 422, in format
2|autocord   |     return self._fmt % record.__dict__
2|autocord   | ValueError: unsupported format character '{' (0x7b) at index 1
2|autocord   | Call stack:
2|autocord   |   File "C:\Users\James\PycharmProjects\tfdiscordbot\GoBOT1234\main.py", line 64, in handle_reconnect
2|autocord   | Message: 'Reconnect in 31...'
2|autocord   | Arguments: ()
```

I'm just using a relatively simple logger for debugging purposes incase anything breaks
```py
bot.log = getLogger()
bot.log.setLevel(DEBUG)
handler = FileHandler(filename='tf2autocord.log', encoding='utf-8', mode='w')
handler.setFormatter(Formatter('%(asctime)s : %(levelname)s : %(name)s | %(message)s'))
bot.log.addHandler(handler)
``` 
Any ideas or help with fixing this would be appreciated

**Comment by rossengeorgiev** [comment]
Hi there, looks like you have some issue with your logging formatter, nothing to do with the `steam` package.

```python
2|autocord   | ValueError: unsupported format character '{' (0x7b) at index 1
```
Check your formatting template, as the code you've provided doesn't seem to match with the error. Good luck
