### ISSUE TITLE
GetUserStatsForGame is throwing internal server error

### ISSUE THREAD

**Issue by ivdmahesh** [ValvePython/steam#229]
Hi,

Do not know what is wrong with this url but it is throwing internal server error -

https://api.steampowered.com/ISteamUserStats/GetUserStatsForGame/v2/?key=xxxxxx&format=json&steamid=xxxxx&appid=1126290

I am using pip steam package and calling - api.call("ISteamUserStats.GetUserStatsForGame",appid =1126290 ,steamid=xxxxx)

Traceback (most recent call last):
  File "speech.py", line 160, in <module>
    call = api.call("ISteamUserStats.GetUserStatsForGame",appid =1126290 ,steamid=xxxx)
  File "C:\Users\mahesh.durga\AppData\Local\Programs\Python\Python37\lib\site-packages\steam\webapi.py", line 167, in call
    return getattr(getattr(self, interface), method)(**kwargs)
  File "C:\Users\mahesh.durga\AppData\Local\Programs\Python\Python37\lib\site-packages\steam\webapi.py", line 332, in __call__
    params=params,
  File "C:\Users\mahesh.durga\AppData\Local\Programs\Python\Python37\lib\site-packages\steam\webapi.py", line 431, in webapi_request
    resp.raise_for_status()
  File "C:\Users\mahesh.durga\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.steampowered.com/ISteamUserStats/GetUserStatsForGame/v2/?key=xxxx&format=json&steamid=xxxxx&appid=1126290

**Comment by rossengeorgiev** [comment]
Hi, this is nothing to do with the `steam` python package. The API is broken, which is common occurrence for Valve.
