### ISSUE TITLE
steam client get_product_info raise KeyError

### ISSUE THREAD

**Issue by zyi1992** [ValvePython/steam#269]
```
2020-06-06 10:53:22.923 [PID:140010] root log.py[line:149] ERROR fetch steam events error
Traceback (most recent call last):
  File "steam_store_event.py", line 108, in main
    run()
  File "steam_store_event.py", line 81, in run
    data = client.get_product_info(packages=package_ids, apps=appids)
  File "/home/steam/.local/lib/python2.7/site-packages/steam/client/builtins/apps.py", line 110, in get_product_info
    data['packages'][pkg.packageid] = vdf.binary_loads(pkg.buffer[4:])[str(pkg.packageid)]
KeyError: '470240'

```

**Comment by rossengeorgiev** [comment]
Looks like package token went live, and the code doesn't handle it well.
