### ISSUE TITLE
Invalid response header in GameServers data

### ISSUE THREAD

**Issue by Kein** [ValvePython/steam#356]
Using the example code form docs:

```python
from steam import game_servers as gs

for server_addr in gs.query_master(r'\appid\550', max_servers=10):
    print(gs.a2s_info(server_addr))
```

```
Traceback (most recent call last):
  File "1.py", line 4, in <module>
    print(gs.a2s_info(server_addr))
  File "C:\Programs\Python385\lib\site-packages\steam\game_servers.py", line 363, in a2s_info
    raise RuntimeError("Invalid reponse header - %s" % repr(header))
RuntimeError: Invalid reponse header - b'A'
```

Is **py module** outdated?

**Comment by Gobot1234** [comment]
This should be fixed on master which you can install using
```sh
pip install -U "steam @ git+https://github.com/ValvePython/steam@master"
```

**Comment by Kein** [comment]
Yeah, I figured. Would be nice if pip module/package was updated
