### ISSUE TITLE
[BUG] can't login on latest version (1.4.0)

### ISSUE THREAD

**Issue by pp0236** [ValvePython/steam#408]
**Description**
cant login on latest version (1.4.0)

**Steps to Reproduce the behavior**
```
>>> client = steam.client.SteamClient()
>>> client.login("****", "****")
Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Users\kath\python workspace\steam test\venv\lib\site-packages\steam\client\__init__.py", line 191, in _handle_logon
    CMClient._handle_logon(self, msg)
  File "C:\Users\kath\python workspace\steam test\venv\lib\site-packages\steam\core\cm.py", line 386, in _handle_logon
    interval = msg.body.out_of_game_heartbeat_seconds
AttributeError: out_of_game_heartbeat_seconds
2022-10-05T14:16:42Z <Greenlet at 0x232a01dd900: <bound method SteamClient._handle_logon of <SteamClient(('162.254.197.54', 27018)) online>>(<MsgProto(<EMsg.ClientLogOnResponse: 751> | CMsgCl)> failed with AttributeError

<EResult.OK: 1>
^^^^^^^^^^^^^^^ ('OK' but cant access username/friend/etc)
```

**Expected behavior**
client should login and no error print to console

**Versions Report**
<details><summary>python -m steam.versions_report</summary>

```yaml
steam: 1.4.0

Dependencies:
                 vdf: 3.4
            protobuf: 3.20.3
            requests: 2.28.1
          cachetools: 5.2.0
              gevent: 21.12.0
 gevent-eventemitter: 2.1
       pycryptodomex: 3.15.0
              enum34: Not Installed
       win-inet-pton: Not Installed

Python runtime:
          executable: C:\Users\kath\python workspace\steam test\venv\Scripts\python.exe
             version: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
            platform: win32

System info:
              system: Windows
             machine: AMD64
             release: 10
             version: 10.0.16299
```
</details>

**Comment by rossengeorgiev** [comment]
I've pushed a new version with the fix. Just update `steam` package.

**Comment by pp0236** [comment]
thanks 👍
