### ISSUE TITLE
No module named webauth

### ISSUE THREAD

**Issue by curiouspers** [ValvePython/steam#42]
I'm very sorry for newb question, but can you put me in right direction on how to find what causes the problem? I'm using python 2.7.
```
>>> import steam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "steam.py", line 2, in <module>
    import steam.webauth as wa
ImportError: No module named webauth
```

**Comment by curiouspers** [comment]
My mistake was that i named the script steam.py
