### ISSUE TITLE
ImportError: Module use of python36.dll conflicts with this version of Python.

### ISSUE THREAD

**Issue by Bluscream** [ValvePython/steam#68]
```
>>> import steam Traceback (most recent call last):   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\pytsonui.py", line 755, in runCommand     res = eval(cmd, self.globals)   File "<string>", line 1     import steam          ^ SyntaxError: invalid syntax  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\pytsonui.py", line 759, in runCommand     exec(cmd, self.globals)   File "<string>", line 1, in <module>   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\steam\__init__.py", line 6, in <module>     from steam.steamid import SteamID   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\steam\steamid.py", line 7, in <module>     from steam.util.web import make_requests_session   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\steam\util\web.py", line 3, in <module>     from steam.core.crypto import sha1_hash, random_bytes   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\steam\core\crypto.py", line 15, in <module>     backend = cryptography.hazmat.backends.default_backend()   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\cryptography\hazmat\backends\__init__.py", line 71, in default_backend     _default_backend = MultiBackend(_available_backends())   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\cryptography\hazmat\backends\__init__.py", line 33, in _available_backends     entry_point_backends   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\cryptography\hazmat\backends\__init__.py", line 50, in _backend_import_fallback     from cryptography.hazmat.backends.openssl.backend import backend as be_ossl   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\cryptography\hazmat\backends\openssl\__init__.py", line 7, in <module>     from cryptography.hazmat.backends.openssl.backend import backend   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\cryptography\hazmat\backends\openssl\backend.py", line 17, in <module>     from cryptography import utils, x509   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\cryptography\x509\__init__.py", line 7, in <module>     from cryptography.x509.base import (   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\cryptography\x509\base.py", line 16, in <module>     from cryptography.x509.extensions import Extension, ExtensionType   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\cryptography\x509\extensions.py", line 20, in <module>     from cryptography.hazmat.primitives import constant_time, serialization   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\cryptography\hazmat\primitives\constant_time.py", line 9, in <module>     from cryptography.hazmat.bindings._constant_time import lib ImportError: Module use of python36.dll conflicts with this version of Python.
```

**Comment by Bluscream** [comment]
Now that I use the right version I get ```
>>> import steam Traceback (most recent call last):   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\pytsonui.py", line 755, in runCommand     res = eval(cmd, self.globals)   File "<string>", line 1     import steam          ^ SyntaxError: invalid syntax  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\pytsonui.py", line 759, in runCommand     exec(cmd, self.globals)   File "<string>", line 1, in <module>   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/lib/site-packages\steam\__init__.py", line 6, in <module>     from steam.steamid import SteamID   File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/lib/site-packages\steam\steamid.py", line 7, in <module>     from steam.util.web import make_requests_session ImportError: No module named 'steam.util.web'  >>> 
```

**Comment by rossengeorgiev** [comment]
My guess is that your python path is wrong, although it seems to locate one of the things. Try prining the contents of `sys.path`.

Also, verify that there is `util/web.py` in `C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/lib/site-packages\steam\`.

**Comment by Bluscream** [comment]
I can confirm the second one. I will post the output of the first one when i woke up

**Comment by rossengeorgiev** [comment]
Closing due to lack of activity.
