### ISSUE TITLE
Error while using onMessage

### ISSUE THREAD

**Issue by d0geda** [ValvePython/steam#91]
Somebody knows how to deal with it?
```
Traceback (most recent call last):
  File "C:\...", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\...", line 208, in onMessage
    messageText = msg.body.message.rstrip().strip("\0")
TypeError: a bytes-like object is required, not 'str'
Thu Apr 13 00:32:57 2017 <Greenlet at 0x54af210: onMessage(<MsgProto <EMsg.ClientFriendMsgIncoming: 5427>>)> failed with TypeError
```

**Comment by rossengeorgiev** [comment]
That version of python?

**Comment by d0geda** [comment]
3.5 because of steampy

**Comment by rossengeorgiev** [comment]
That code doesn't appear to be part of the `steam` package.

**Comment by rossengeorgiev** [comment]
Closing this due to inactivity.
